app:
    services:
        ROSTELECOM: http://localhost:8082/rostelecom
    cars:
        LINKOLN :
            name : linkoln
            prioritized-send-type: HTTP
            send-types:
                - SMS
                - HTTP
            codes:
                - unlockDoor
                - lockDoor
                - engineOff
                - engineOn
        LADA :
            name : lada
            send-types:
                - ERROR
            codes :
                - error
                - engineOff
